name: Rust Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@main
        with:
          token: ${{ secrets.TOKEN_FOR_UPDATES }}
